### PR TITLE
Respect the options field in the meta file

### PR DESCRIPTION
**Pull request by dorner**
See https://github.com/mateodelnorte/meta/pull/49
This will make it so adding this config will not require you to hit Enter every time you do `meta git whatever`.

Also I realized that the "c" option was a) ambiguous and b) didn't actually do anything, so I removed it.

### CODE REVIEW

**Comment by mateodelnorte** [comment]
Thanks for the PR, @dorner. Just so I follow the original pain point, what do you mean by having to hit enter every time you do a `meta git whatever`. `meta git status` should loop through all your repos in one command. Same with branch, checkout, etc. The only things that should cause you to have to touch your keyboard again are things that steal the framebuffer, like `meta git diff`. You'll have to `q` through those. (though I have ideas for v2.0.0 to make that not necessary). 

If you're having to hit enter each time meta is looping through git commands, I wonder if you have a git auth problem. If you're on windows, this can sometimes be fixed with the [credential helper](https://github.com/Microsoft/Git-Credential-Manager-for-Windows).

**Comment by dorner** [comment]
@mateodelnorte sorry - was totally unclear here :o I meant when I'm trying to use `meta git blah` inside a child project instead of the parent project. There's a confirm dialog that pops up that asks whether I really want to use `meta` since I'm not directly inside a meta project, but a meta sub-project.

This option would disable the prompt and just assume I'm always OK with calling `meta git blah` inside a subproject.

**Comment by mateodelnorte** [comment]
Apologies. Super swamped. I'll try to merge this weekend. Thanks.

**Comment by dorner** [comment]
No worries - thanks very much!

**Comment by dorner** [comment]
@mateodelnorte took another look at this based on our discussion here: https://github.com/mateodelnorte/meta/pull/49 Trying to pull this into a configuration gets me into a recursive logic bomb where I need to figure out whether this confirm dialogue is required by looking at the config, but I can only look at the config once I've found the new config file, which I might need a dialog for -_-

Can we just replace the dialog with a warning message so users don't have to tap Y/N? That would simplify this immensely.

**Comment by mateodelnorte** [comment]
Can you remind me what this PR is all about?

**Comment by dorner** [comment]
LOL @mateodelnorte this was about the confirm dialog that pops up when you try running a meta command from inside a subproject directory rather than inside the parent directory. I wanted to have a configuration that would disable this confirm dialog, but changing it to a configuration has proven to be a lot more trouble than it's worth, so I'm asking if I can just disable the confirm dialog and print a warning instead.

**Comment by mateodelnorte** [comment]
I'm thinking the entire part of asking if you'd like to chdir and execute in a different location doesn't belong in this package. It probably belongs in https://github.com/mateodelnorte/meta-exec/. 

I think some people like being able to run against a .meta file without having to change directories before executing. So, the warning would cause us to have to choose one of two behaviors and eliminate the other: warn and run in parent, or warn and not run. 

I'm wondering how else we can solve this.

**Comment by dorner** [comment]
@mateodelnorte I guess my main question is what problem are we trying to solve with this prompt? If someone is running a `meta` command, and they are in a subproject, I think it's reasonable to assume that they wanted to run that command on all subprojects inside the main one. Why else would they be calling a `meta` command? Maybe you can provide an explanation but I can't really see why someone would want to be prevented from doing this.

**Comment by dorner** [comment]
@mateodelnorte in other words my question is why this commit happened: https://github.com/mateodelnorte/meta-loop/commit/67801280b11f5c55c918f809dd09d5fdaceeb951

We can solve my problem just be reverting this and having `confirmInMetaRepo` be set to false.

**Comment by mateodelnorte** [comment]
The intention is that if you run something like `meta exec ls` in a child directory, it will function like `loop ls` after asking you if you'd like to run in the current directory. You could potentially write any plugin that could leverage loop's behavior to run against the current directory and all child directories, and therefore run it from anywhere.

**Comment by mateodelnorte** [comment]
Looks like that's currently working for .meta repos that have child repos directly under the parent, but breaking in meta repos, like meta itself, that have them listed within some specified folder. Looking at that now.

**Comment by dorner** [comment]
@mateodelnorte yep, I get that behavior. My question is why we need to prompt the user whether they want to proceed. Can we just assume that the fact that they're calling a `meta` command inside a child project indicates that they want this behavior? It gets noisy with my command, which always assumes it's inside a child project.

**Comment by mateodelnorte** [comment]
There are some plugins for which that doesn't make sense. You wouldn't want to `meta git status` in some random dir, for instance. It's a nice feature to be able to do `meta git status` without first changing dirs to your meta repo.

**Comment by mateodelnorte** [comment]
With the current behavior, all you have to do for `meta git status` to work everywhere is hit enter once.

**Comment by dorner** [comment]
@mateodelnorte that's not what I see. If you run `meta git status` from a child repo, it first prompts you as to whether you actually want to run it on all child projects. It doesn't do it with a single enter press. I'm trying to figure out why that prompt is necessary and we can't just always run on all child projects if you're in a child project.

**Comment by mateodelnorte** [comment]
I'm saying hit enter one extra time.

**Comment by dorner** [comment]
Right - and I'm asking why that extra enter is necessary. I still haven't heard a case where someone would *not* want to run a meta command on all subprojects no matter where they are in the project tree.

**Comment by mateodelnorte** [comment]
We might not be getting each other's ideas over text. Note, there are places where I purposefully said "directories" and not "repos" or "projects". 

> The intention is that if you run something like meta exec ls in a child directory, it will function like loop ls after asking you if you'd like to run in the current directory. You could potentially write any plugin that could leverage loop's behavior to run against the current directory and all child directories, and therefore run it from anywhere.

> There are some plugins for which that doesn't make sense. You wouldn't want to meta git status in some random dir, for instance. It's a nice feature to be able to do meta git status without first changing dirs to your meta repo.

So, it's not an interesting feature if you only ever want to run things against top level repo dirs. But there are some commands you might want to run against non top level repo dirs. It comes down to whether you 1) want `meta exec X` to be something that only runs against top level repo dirs, or can also be run against any arbitrary dirs, via `loop` functionality, or 2) want that behavior to be accessible in any plugin someone might want to make.

**Comment by mateodelnorte** [comment]
And the enter is necessary, because for some plugins, you don't want the above behavior. So, an extra enter gives you the ability to do both.

**Comment by dorner** [comment]
Ahhhh - I get it now - that was the distinction I was missing. Thanks!
In this case it sounds like this needs to be a plugin-level configuration, where when plugins register themselves they can provide options as to how meta behaves, rather than user-level configuration.

I'm going to close off this PR and rethink how we can implement this better.

**Comment by mateodelnorte** [comment]
I think what we can do is 1) implement your meta-config plugin and 2) make a get-meta-file config option to never ask. It will essentially act like a feature flag. 

So, there would be a config option like: 

{
  'get-meta-file.always-continue': true
}

Thoughts?

**Comment by dorner** [comment]
The issue is that this config file would have to be included every time the plugin is used. This shouldn't live in a configuration file because it should always be true for some plugins and always be false for others - it wouldn't be repo-specific.

I think it makes more sense for the plugin to declare its own configuration when it registers itself. This way the configuration doesn't need to live inside the repo, it lives inside the code.

**Comment by mateodelnorte** [comment]
Well, if someone just always wanted to disable the behavior – it would work. However, yes, if you want to make it never do that for a specific plugin, but not others, we'd need to think of something else. 

I think this is actually quite simple. We can just make `[meta loop](url)` take an options variable [here](https://github.com/mateodelnorte/meta-loop/blob/master/index.js#L10). Each plugin can then either specify nothing, by default, or specify { confirmInMetaRepo: false }, for example [here](https://github.com/mateodelnorte/meta-git/blob/master/bin/meta-git-status#L21). 

So, it's no longer config. It's specified by the plugin – which is what you want.

**Comment by dorner** [comment]
@mateodelnorte Yep, for sure! That would work just fine :)

**Comment by mateodelnorte** [comment]
Did you wanna take a swack at those two PRs, or want me to get 'em?

**Comment by dorner** [comment]
I likely won't have time over the next couple of days unfortunately. If you can get to it before then, go for it - they should be pretty small.

**Pull request closed without merging**
